### ISSUE TITLE
l2rmats filter really doesn't like comparing opposite strands

### ISSUE THREAD

**Issue by leipzig** [Xinglab/lr2rmats#4]
Hi - virtually any opposite strand query.sam vs rRNA.gtf alignments seem to trigger a `[trans_exon_comp] Strands of exons do NOT match.` error. Should I be converting all the rRNA strands to `.`?

here's a reproducible example:

rRNA.gtf
```
chr1	hg38_rmsk	exon	629499	629570	429.000000	-	.	gene_id "tRNA-Gln-CAA_"; transcript_id "tRNA-Gln-CAA_"; 
chr1	hg38_rmsk	exon	632619	632685	432.000000	-	.	gene_id "tRNA-Ser-TCA(m)"; transcript_id "tRNA-Ser-TCA(m)"; 
chr1	hg38_rmsk	exon	1883669	1883765	515.000000	+	.	gene_id "LSU-rRNA_Hsa"; transcript_id "LSU-rRNA_Hsa"; 
```

samp1.minimap.sam
```
@SQ	SN:chr1	LN:1153837
@PG	ID:minimap2	PN:minimap2	VN:2.12-r827	CL:minimap2 -ax splice -ub -t 1 test_data/genome/genome.fa.smmi test_data/read/SRR5009429.fasta
SRR5009429.9366 0       chr1    134065  1       24S1M1D49M1D16M115855N1I34M1D9M1D70M1D109M1I14M1001S    *       0       0       AAGCAGTGGTATCAACGCAGAGTACTTTTTTTTTTTTTTTTTTTTTTTTTTTTGAGATGAAGGCTTGCTCTGTCTCCAGGCTGGAGTGCAATGGCACGATCTCAGCTCACTGCAACGTCCACCTCCGGGTTCAAGCATTCTTCTGCCTCAGCCTCCAGAGTAGCTGGGATTACAGGCGCCTGCCACCACACCCAGCTAATTTTTCTATTTTTAGTAGAGACAGGGTTTCACCATCTTGGTCAGGCTGGTCTCAAACTCCTGACCTCAGGTGATCCACCCGCCTCAGCCTCCCAAAGTGCTGGGATTACAGGCGTTGAGCTACCGCGCCCGGATCCGTAAGTGATCTTACATCAACTAGAACATACTTAAGAGTGAAAAATTATACAATGGTTTCTTCCCTCTCCTGTAGAAATGTTACCATAATTAAATGTTTGATCAATTGCTAAATCACAACTTACAATATGAAAATCTTCATATACTTCAAATATACTGAAGAAAATGTCCTACATGTAACTGAGGTGCGCATCCACCTGAATGAACAGCACGAAACGCTATTAAAGTGACACTAGAAGCCCAGGCACAAATCATACACAGACACAAAAAAGCTCCAGATCCCACTCAGGAAGAATGCACCAACACATTCGCATTTATTTTCTTTTTTTTTTTTAAAGCAAATGACAAAGACCCAGTTTACCAGCTTTACTTTTTTAAACCTAAGCTTAACATTACATATTTAAACAATTGTCAAACTTACTAAGTTGCCAGCATTCATGCACAACTAGAAAACATCCTTAATTTATATTAACCAGAAATGTATTACCATTAATGTATTAATATCTTTCACTACTAAATACTGAAAAAATTGAAATTATTTCTGTAGAAGAATCGTCCTGGCAATGTTAACTTCACAGCAGGCCGACACTACGTGGCTCACATTTCAGACACAATGAAAAGCAGGTCCATGCTGGTGTTAGTGTACAATCTTGTCCTACACTAAAGAGTCAAGACTCACCTTGAGTACGTTTAATAAAAAGCAAAGTGCATACAGAGATTTACAACAATTTTAAAGACAAAAAAAATGGTCCTATTATGTGGTCCAACAATCAACTCAAAAGTCTATGACAAATAGAGGCTCCGATGAGCTGTTTATAAATACTTTAGGTACAATTATACTGAAAGTCGAGTTCGTTTGAAATCTTCAAAAAAATGTTCCTGTTAATCCTCAAATGGTGCTTGTTATAGTTTAACATTTCTGTTAAGTGCGTGCGTTTGAATTACTTGTTATCCAAGCGCAGCAGCTGCTCCTTACTCTGCGTTGATACCACTGCT *       NM:i:36 ms:i:196        AS:i:162        nn:i:0  ts:A:+  tp:A:P  cm:i:14 s1:i:82 s2:i:106        dv:f:0.1136     SA:Z:chr1,1069470,-,662S643M55396D24S,24,367;
```

lr2rmats filter samp1.minimap.sam -r rRNA.gtf -v 0.67 -q 0.75 -s 0.98
[trans_exon_comp] Strands of exons do NOT match.

thanks for your help and awesome C code!

**Comment by yangao07** [comment]
Hi Jeremy,

Thanks for pointing this out. 
Actually, this is caused by a bug in the function of reading annotation file.
It is fixed now.

We appreciate any feedback from you.
Thank you.

Regards,
Yan

**Comment by lisagrigoreva** [comment]
Hello, there is still an issue during the reading of the GTF file
=== 07-01-2022 10:54:34 === [read_anno_trans] reading transcript annotation
[trans_exon_comp] Strands of exons do NOT match

**Comment by yangao07** [comment]
Hi @lisagrigoreva , can you provide the file that causes this error msg?

**Comment by huziouziou** [comment]
Hello, I also meet this issue when reading GTF file of Nile_tilapia downloaded from Ensemble
=== 03-02-2023 15:08:09 === [read_anno_trans] reading transcript annotation from data/gtf/rRNA.gtf ...
[trans_exon_comp] Strands of exons do NOT match.
I used command `grep -wi 'rRNA' Oni_genome_109.gtf > Oni_rRNA.gtf ` to create rRNA.gtf
I don't know if it's the GTF of Nile_tilapia itself or the way I generate rRNA.gtf
```
@SQ     SN:MKQE02001685.1       LN:7402
@SQ     SN:MKQE02001493.1       LN:7319
@SQ     SN:MKQE02001957.1       LN:7260
@SQ     SN:MKQE02001145.1       LN:5393
@PG     ID:minimap2     PN:minimap2     VN:2.17-r941    CL:minimap2 -ax splice -ub -t 8 data/genome/genome.fa.smmi data/read/T6_long.fa
@PG     ID:samtools     PN:samtools     PP:minimap2     VN:1.10 CL:samtools view -h samp1.minimap.sam
5846f947-45a3-4d54-b2c9-d4dc85339258	4	*	0	0	*	*	0	0	GTGTGCTTCGTTCGATTTGATTTGGTCGTTAACCAGTTCGCCATACCGTGACAAGAAAGTTGTCGGTGTCTTTGTATTGCCTGTCCGCTCTATCTTCCCTACACGACGCTCTTCCGATCTACCATTTAGGTATGTACATTAACGTTTTTTTTTTTTTACTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTATCATGCCCCCCAAATTTATTTCTTGAACCTGTCAGGGCCCCCCCAATTTTGGGGCTTTCCCACAATTTGGGGCTTTCCCCAATGGTTGGGGCCAGGACCCCCCTTCTGCCCCTCCTCTTCTTTTGGGGCTTTTCCCCATGCCCATTTTTGGGGTTTTCCCTTTAACTTTTCCCCATTTTTGGGACATTTTCTCCCCTTTTCCCCATGTCTGCGTTGATGCCATAGCATGATATCAACC	*	rl:i:123
9afa271d-5d9f-4721-bb2a-d5cab60dd6e9	4	*	0	0	*	*	0	0	GTTATGCTTCGTTCAGTTTAGGTAGGTGTTTAGCAGTCCGCCATCTACCGTGACAAGAAAGTTGTCAGTGTCTTTGTGACTTGCCTGTCGCTCTATCTTCACACGACGCTCTTCCGATCTTCCATGCCAGTTCAACACTATACTCATTTTTTTTTTTTTTTTTTTTTTTACAGGTTAGCAAAATATTTTATTATAGTAAAACATACCATACACAGAGGAGAACAAATGGTTTATATTTTATCTGTCCCATCAAAGCAAATACCTTTATAATACTTCCCACTGGCTTAAAAAGAAATGCTAATAGAAATAATTTCATTATTAAAAATAGATAGTGTTTCCTATTTATTTTATTCTATATTAGAAGGCAAAATATTGAGATGATGATATGGCTTAAATATATTAAAATTTTCCCTCTGGGGAGCTAGTCTCTCCATCTCTAGCTAGACCACACATGGAATGAGTTCAGGCTGCATGACGGGTATAAACCCACATTAGGTGTAAATTCAATATCTTCAACCAAGGTACCTGAGTTTGACAAAGAGGAGTCTTGGATACCTGATACAATGTTTTCTTCTCTTGCATCCCATGCTCTGCGTTGATACCACTGCTGCAATATCAGCACCAACAGAAACACAAAGACACCGACAACTTTCTTGTC	*	rl:i:27
b126e482-3140-426c-9fb9-50aa0284ede2	4	*	0	0	*	*	0	0	GATGTACTTCGTTCAATCAAATTTGGGTGTTTTATGATTCGCCATACCGTGACAGAAAGTTGCCGGTGTCTTTGTGACTTGCCTGTCGCTCTATCTTCTACGACGCTCTTCCGATCTGTGAGCCCACCCTTGTTTGCACCCACGATTTTTTTTTTTCAGTTGATTTTATTGTCGGTACATTTGCCATATTTCTGGCTTACATTGAAGCAGTATGAACGGCGCGCACAGTAGTGCCTGTCAAGTGGCTGGCCGCGGTATTGCATATCCGAAGACGCTCGCGCGGGCAGCTGATCTTGCCATTCTCATCCACCCAAAGGCGCGCGGCTGCCGGCTTATTTTTCTTTCTCTTATCGCCGTTCCTTCTTGGGAGTCATTAAGACTTCTTCTTCCCTTTTCTTAGCACCACCACGAAGTCTTAGCACCAGGTGAAGGTTGATTCCTTCTGAATGTTGTAGTCGGACGGTGTGCGTCCATCACTCGCTGCTTCCCAGCGAAGATCAGCCGCTGCTGATCCGGAGGGATGCCCTCTTATCTGGATCTTGCTTTTACATTTCCTGTATTATCAGAAGGTTCAACCTCGAGGGTGATGGGTTTTCCCCGCGAGGGTCTTCACCGTCTGCATGCCCGTATGCTCTGCGTTGATACGCCTTGCAATATCAGCACCAACAAAACACAAAGACACCGACAACTTTCTTG	*	rl:i:0
b7ab82d1-586f-4c95-8050-935c846beba5	0	LG15	28067721	31	180S21M1I1M2D18M1D33M1I23M1I31M1D5M131S	*	0	0	CATACTTCGTTCGTATTTATCAAGATTTGGGTGTTTATGGTCGCCATACCGTGACAAGAAAGTTGTCAGTGTCTTTGTAATGACTTGCCTGTCGCTCTATCTTCCTACACGACGCTCTTCCCGATCTTGCGCAGGTTAGAGCCAACACAGTACGTTTTTTTTTTTTTTTTTTCTCACGGCCTGTCAAAATGAGGTGCAGTATGGTGGAAGCATGTAGGTATCAACTGGGACTGATTTTTAGATACGAGTTGTGATTTTTTCTGGCCTTGTGTTGTAAAGCAACAGTGTGTGACTTAATAAAACTAAACCTCTGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATAAATTAAAAAAAAAAAAAAAAAATCCGACTTATTGGGGACCACACAATATCCAGATCAGG	*	NM:i:10	ms:i:104	AS:i:104	nn:i:0	tp:A:P	cm:i:16	s1:i:85	s2:i:0	de:f:0.0652	rl:i:124
70157fe7-4798-46dc-b03e-b09c65c5525c	4	*	0	0	*	*	0	0	CAGTGTGCTTCGTTCAGAGTTTACCTCAAATTTGGGTGTTTATGATTAGCCATATTGACAAAGAAAGTTGTCGGTGTCTTTGTGACTGCCTGTCGCGCTCTATCTTCCACGACGCTCTTCCGATCTTCTATACGTGTTTCGATGCAGAGATGATTTTTTTTTTTTTTTTTTGTTTTAATAAACATTTATTGATGCAACCTTGTTACACCCTTAGAAGCACCTTCTGGAAGAACCACTTATTCTTGCCAGTCTTGTACCTCTCCTCAAATTTCACCTTGCTTCACGTCTTTGCGTTTTAGGCGGGATCCCTGAACACGTCCTTGTTGACCACTGTTTGTCAGAATATCCAAATACCGGGTGGGCATCAAGTGGTTGTAGTTGTAAACAGCCACGAAGGACTTGATCTTGGAGCCAGCACAGCGATCTTTTTTGCCCATGGCAGCAGTCTGCCGCGGGTAGCGGTCGTGCCGGCCACTAAGGCATGGCTGTACGGCCGGTCAGTGCCATCGTCGATGTTCTTCACGATGACGGCCCCCTTACGCCCCGGTGGCAGCCGGCCAACGCAACACCACCTTCCCCGGCTTCATAAACTTCCCCATCTCGAGGCTCCGCTGCGATGGCGCTGGTCGACCCCATGTACTCTGGTTGATACCACTGCCCGCAATATCCAGCACCAACGGAAACACAAGACACCGACAACTTTCTTGTC	*	rl:i:40
a6e782f7-7ec1-4bd9-8bda-4c53dbd68d77	4	*	0	0	*	*	0	0	CGGTATTGCTACGTTCAGTTTCTCAATTTGGGTGTTTAGCAGGTCGCTGTTCGCCTACCGTGACCGAAAGTTGTCGGTGTCTTTGTGTTTCTGTTGGTGCTGATATTGCAAGCAGTGGTATCAACGCAAGTACATGGGATAAACATAATCTATTCATACTGACCCTATCATTCACTCTGACATCCTACTAACTTTGCACTAAACTTCTGACTAGCCCAAATAAACCCAGACCCGAAAACTATCTCCTTACGAATGTGGTTGACCCCCTAGGTTCTGCCCGATTACCATTCTCAATCCGATTCTTCTAGTAGCCATCCTATTCCTCCCTTTTCGACTAGAAATCGCCCTCCTACTACCACTACTTGAGCCATCCCAACTAGAATCCCCCATAACCACCTTAACCTGAACCTCATCGCCTCCTCCTCCTAACACTAGGGCTCATTTACGAATGAATCAAGGCGGATTAGAATGAGCAGAATGAAAAAAAAAAAAAACGGGCGGAGGCTCTTAGCGCGTGTTTCTACAGATCGGAAGAGCGTCGTGTAGGAAGATAGAGCGACGACAAGTCACAAAAGACACCGACAACTTTCTTGT	*	rl:i:17
d4dc1593-2189-4998-962a-d6a90a59a00b	4	*	0	0	*	*	0	0	AATACTACGTTCGATATGGGTGTTTATGATGTCGCCTACCGTGACAGAAAGTTGTCGGTGTCTTTGTGTTTCTGTTGGTGCTGATATTGCGCAAGCAGTGGTATCAGCGCAAGAGTACATGGGAAATTCTCTGGCGAAGCCAAAGTCATTTGCGCTGGTATCAGACAGCGAACCAGGTTTGCCTCTTTGCCGCAAGTGAGTGGATCACGATCTGGCTCGTTGTTCCTTTTCTATGCATATACTAACAGAATTTAGCTACAAGAGGTATGAGGCAGCAACAGGAAAATGGAGACGAACTGAATTTTCACCCTCAACTCTCAGGCATGGCAACAGAGAATGTTTGAGAGAACAGATGGGCCAGAAATGAAAGTTGCCGGGATCGCTGTCACTGAATCAGGTGCCTGGAGGTGGAAGTAGAAGCTCTCTTTGCTCATTTCATTATGAAAAAGTTTTATTTTCTGTCAATTACTTTCATTTTACTCTAAATGGCAATGTGTCACATCATTTCTGGGGGAAAATTCTGCTGTTATGAGACAATGTAACTTTGTACATAATGCATGTCAAATAAATATCTAATGGTTCAGTCACGAAAAAAAAAAAAAAAAAAAAAAATACAACCTCACAAGACTTTCTTATCGCAGATCGGAAGAGCGTCGTGTAGGAGGAAGAGATGGGGCATTCAGGCAAGTCACAAAGACACCGACAACTTTCTTTTGTC	*	rl:i:28
25ef5bd9-6b5d-4f06-95d2-9c86611baaac	4	*	0	0	*	*	0	0	GTTGTACTTCGTTCAGTTTGGAAGAATTTGGGTGTTTAACCAGTCATCGCCTACCGTGACAAGAAAGTTGTCGGTGTCTTTGTGTTTCTGTTAGTTGCTGATATTGCAAGCAGTGGTATCAACGCAGAGTACATATGGGCAAACTGGGGCGATTTTAATGGAAAAGCTTTTTAAGCTGCTTTAATTTAAGAAAAAGCGCTCAATACGCGCTCTTTAAAAAGCTCCTGAATTTAATTTTCATTTTCAAAAACCACAAAAAGCTTTAAAAAATGTAATTTTGTCCCCAAATTAGGGCCGGGCCCGGGCAGCGCAGGCGGGGCAGCCGGTTTGGGAAGTGAAAATACGGCATTTTCAGGCTCAAGGATGGATTGAGAGGAGCCAATTTTGAGAGAGCAGGAAAACTGAAGAGTGAGAAAATTAGGTCGGCAGGAAAGGAAAGTTTTCTTCGCAGTGGCCCCATCTGGGGGAAAAAGGACTTTTGGTAAAATACGGCAGTTGGGCAGGAGCAGAGAAGAGAGGAAAAAAGAAAGACAGAAAATAGAAAAAAAAGAGAGAAAATAGAAAATCAGAAAAAAAAGAAAATAGAAAAACTTGAAAAAGAGCAAGAAACAAAATTGCAAAAATAGAAATTGGAAAAAGAAAAATTGAAAAAACATAGTAAGAATGGAAAAAAAAGAAAGAAAAAAGAAGAAAATTTGAGAATAGAAGAAACTAGAAAAAAATTTGTGAAAATAGAAGAAATTAAAAAAAGAAAATTGAACAAATAGAAAATAGAAAGAATATAGAAAAAATAATAGAAAAATGAAAATAGACTGTAAATAAATGAAAAATACAATTAAAAATGAAACTAGGAAAAAAAAAAAAAACCTTTTTGTAGCATCGCTTGACATGAAAGATCGGAAGAAGCGTCGTGCTTAGGAAAGATAGAGAGCGACAGGCAAGTCACAAAACACCGACAACTTTCTTGT	*	rl:i:68
eb8d3fcb-147a-42b0-83c5-8c5ba14e99df	16	LG8	27392883	60	68S21M1I27M1D43M3D23M1I18M3D39M3D1M1D32M4D27M2D36M3I7M2D28M1D5M1I118M1I47M1D19M1D7M2D39M172S	*	0	0	CAAGAAAGTTGTCGGTGTCTTTGTGACTTGCCTGTCGCTCTATCTTCCTACACGACGCTCTTCCGATCTATGTGATAAACCAATACTGCTCTAAGAATTTATATAAGACTGTTGCGATTTGAGCCATGGTCCATGCCATGTCTCAACAGGAGGGATGATGGCAGTAGAGCAACATTTTTATACTTCTAGGATTTAATACTTTAAAAAAATTGTAGGTCATGGCGGGTATGTTGCAAGCACACCTGGGTAATTTATGACCTAAGAGAGGGAAATTTGACCCAGTCACACATTTCAAGTTATTCATGGACTTTATAGAGCTGTCCAACTGTAATAGCTAAGGCAATTGCTCCAGTGATAGTGTGCCTTTTTCAAAGTGGTAGAAAATCATCCCAACTAGGAAAGCAGATGCCATTTCAGTTACCAAAGCAATATGCAAGAATATCAATGTGGAACACGGGATTCCGGAGATTATTTATAGTTATAATGGTCCACATTTTGTAAAATGAAGTGATTGGGTTAATGGCACAGCATCTAAAACATCATTGTTATTTCACCTACAAAGTACAGGCTGGTAGAGGACCAATGGGACAGTAAAGCCAAGACTTAGAAAAAAAAAAAAAAAAAAAGCCGGGCACACTGTAAGCTGTGGACATAGATCGGAAGAGCGTCGTGTAGGAAGATAGAGCGACAGGCAAGTCACAAAGACACCGACAACTTTCTTGTCACGGTAGATGGCGATCCATAAAACACCCAAATTCTTCCAAAAAAAACTGAACGAAGCATG	*	NM:i:49	ms:i:418	AS:i:418	nn:i:0	tp:A:P	cm:i:77	s1:i:384	s2:i:147	de:f:0.0632	rl:i:24
a89ed234-a4c5-45af-a92e-37e7c4f77c3c	16	MT	1091	60	12S22M1I21M1I34M1I17M1D24M2I10M1D17M2D30M1D15M1I10M1D68M2I7M1D26M1D70M2I26M1D19M1D2M2I29M1D17M2I2M1D5M1D45M3I37M1D8M3D7M1D28M2D3M1I4M2I5M1D22M2D6M1I33M1D26M1I2M1D6M1D15M2I7M1I43M1D10M1D27M4D57M172S	*	0	0	TCTGGAGCCTGTAATAGCTAGCCCACCCATCAACTCCCAAACCCACCCCATCTCTACCCCCCAAACACACCACCACACAACAAACAAACCATTTTTTCCACCTAAGTACGGCGACGAAAAAGGACCTAGGAGCTAAATAGAGAAAAATTGCAAGGGAAAGCTAAGAGAAGTGAAACAACCCAGTAAAGCACTAAAAGCAGAGACCACTCCCTCGTACCTTTGCATCATGATTTAGCCAGAAAACCTTAAGCAAAAAGCATTATAGTTTAATACCCTGAAACTAAGCGTGAGCTACCTAAGACAGTCTAATTTATAGGACCACCTGTCTCTGTGGCAAAAGAGTGGGAAGAACTTTGAGTAGAGGTGACAGACCTACCGAGCCTAGTTATAGGCCTGGCTGCCTGAGAACTGAATAGAAGTCAGCCCTTTGCACCCTCTCCATCTCATTGGCTCAAGGCCTCCATACCGAACAAAGAAATTAAGTGAGTTGTATCAAAGGGGTACAGCCCTTTTGAAACAAGACACAACTTTCCAAGGAGGGTGGGGAAGATCACAACAAACCTAAAGGTTTAATGTCCTAGTGGCCTAAAAGCCACCACTTAGAAAGCGTTAAAGCTCGCACATTATACTCCAATCCCTTTAATAAGGACAACACAATCTTATCCCTAGAACCTACCAGGCCATTCCATAGAATTATGGAAGGTTTATGCTAATATGAGTAATAAGAGTAGGTCCCTTCTCCCCGCACAAGTGCGTAATTCTGGAACGAACCATTCACCGACCATTAACGGCCCCAAAATAAAGAGGCATTAGACAAAAATAAAGAACTAGAAAACCACCTAGCTCCCCCACCGTTAACCCCACACTGGTGTGCCAACTGGGAAAGACCAAAAAAAAAAAAAAAAAAAAAAGCAGAAACTGGCGCAATTGAAGGCTCAGATCGAAGAGTTCGTCGTGGCGGGAAGATAGAGCGACAGGCAAGTCAGGCTGTTATCATCCGACAACTTTCTTTGTCACTTGGGTAGATGGCGGATCGGCAAACACCAAATTCACAACTGAACGAAGGTCATG	*	NM:i:115	ms:i:551	AS:i:551	nn:i:0	tp:A:P	cm:i:64	s1:i:359	s2:i:0	de:f:0.1086	rl:i:43
```

**Comment by yangao07** [comment]
Can you upload the rRNA.gtf  here?

**Comment by huziouziou** [comment]
[rRNA_gtf.txt](https://github.com/Xinglab/lr2rmats/files/10887262/rRNA_gtf.txt)
OK，this is rRNA.gtf in TXT format

**Comment by yangao07** [comment]
@huziouziou , turns out this is due to there being multiple transcripts sharing the same transcript name in the GTF file.
This error is fixed in the latest commit, please try it out.
